'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '@/context/AuthContext';
import { Bell, ShieldCheck, Globe } from 'lucide-react';
const AdminHeader = () => {
    const { user } = useAuth();
    return (_jsxs("header", { className: "h-16 bg-slate-50 border-b border-indigo-100 px-8 flex items-center justify-between sticky top-0 z-10", children: [_jsx("div", { className: "flex items-center space-x-4", children: _jsxs("div", { className: "flex items-center space-x-2 px-3 py-1 bg-amber-100 text-amber-800 rounded-full text-xs font-bold uppercase tracking-wider", children: [_jsx(Globe, { className: "w-3 h-3" }), _jsx("span", { children: "Global Network Architecture" })] }) }), _jsxs("div", { className: "flex items-center space-x-6", children: [_jsxs("div", { className: "flex items-center space-x-2 text-slate-600", children: [_jsx(ShieldCheck, { className: "w-5 h-5 text-emerald-500" }), _jsx("span", { className: "text-xs font-medium", children: "System Integrity Verified" })] }), _jsxs("button", { className: "p-2 text-slate-500 hover:bg-white hover:shadow-sm rounded-lg transition-all relative group", children: [_jsx(Bell, { className: "w-5 h-5" }), _jsx("span", { className: "absolute top-1.5 right-1.5 w-2 h-2 bg-indigo-600 rounded-full ring-2 ring-slate-50 group-hover:ring-white" })] }), _jsx("div", { className: "h-8 w-px bg-slate-200" }), _jsxs("div", { className: "flex items-center space-x-4 bg-white p-1.5 pr-4 rounded-xl shadow-sm border border-slate-100", children: [_jsx("div", { className: "w-9 h-9 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-bold shadow-indigo-200 shadow-lg", children: "S" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold text-slate-800", children: (user === null || user === void 0 ? void 0 : user.name) || 'Super Admin' }), _jsx("p", { className: "text-[10px] text-indigo-500 font-black uppercase", children: "Core System Maintenance" })] })] })] })] }));
};
export default AdminHeader;
