'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminSidebar from '@/components/layout/Sidebar';
import AdminHeader from '@/components/layout/Header';
import { Globe, Users, CreditCard, Activity, ArrowUpRight } from 'lucide-react';
import { motion } from 'framer-motion';
const AdminDashboard = () => {
    const adminStats = [
        { name: 'Active Tenants', value: '2,842', icon: Globe, color: 'text-indigo-600', bg: 'bg-indigo-100' },
        { name: 'Total Users', value: '45,921', icon: Users, color: 'text-amber-600', bg: 'bg-amber-100' },
        { name: 'MRR Growth', value: '$842.5k', icon: CreditCard, color: 'text-emerald-600', bg: 'bg-emerald-100' },
        { name: 'System Uptime', value: '99.99%', icon: Activity, color: 'text-blue-600', bg: 'bg-blue-100' },
    ];
    const dummyTenants = [
        { id: '1', name: 'Global Tech Corp', slug: 'global-tech', plan: 'Enterprise', status: 'Active', users: 450 },
        { id: '2', name: 'Indie Studio', slug: 'indie-studio', plan: 'Pro', status: 'Trial', users: 12 },
        { id: '3', name: 'Mega Retailers', slug: 'mega-retail', plan: 'Enterprise', status: 'Active', users: 1205 },
        { id: '4', name: 'Micro Solutions', slug: 'micro-sol', plan: 'Free', status: 'Suspended', users: 2 },
    ];
    return (_jsxs("div", { className: "flex h-screen bg-slate-50", children: [_jsx(AdminSidebar, {}), _jsxs("div", { className: "flex-1 flex flex-col overflow-hidden", children: [_jsx(AdminHeader, {}), _jsxs("main", { className: "flex-1 overflow-y-auto p-10", children: [_jsxs("div", { className: "flex items-center justify-between mb-10", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black text-slate-900 tracking-tight", children: "System Overview" }), _jsx("p", { className: "text-slate-500 font-medium", children: "Administrative control panel for global SaaS state." })] }), _jsxs("div", { className: "flex space-x-3", children: [_jsx("button", { className: "px-5 py-2.5 bg-white border border-slate-200 rounded-xl font-bold text-slate-700 hover:bg-slate-50 transition-all flex items-center shadow-sm", children: "Export Logs" }), _jsx("button", { className: "px-5 py-2.5 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-500 transition-all shadow-lg shadow-indigo-200", children: "New Tenant Instance" })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-10", children: adminStats.map((stat, idx) => {
                                    const Icon = stat.icon;
                                    return (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: idx * 0.1 }, className: "bg-white p-7 rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 relative overflow-hidden group", children: [_jsx("div", { className: "absolute top-0 right-0 p-4 opacity-10 group-hover:scale-150 transition-transform", children: _jsx(Icon, { className: "w-16 h-16" }) }), _jsx("div", { className: `w-12 h-12 rounded-2xl ${stat.bg} ${stat.color} flex items-center justify-center mb-6`, children: _jsx(Icon, { className: "w-6 h-6" }) }), _jsx("h3", { className: "text-slate-400 text-xs font-black uppercase tracking-[0.1em]", children: stat.name }), _jsxs("div", { className: "flex items-baseline space-x-2 mt-2", children: [_jsx("p", { className: "text-3xl font-black text-slate-900", children: stat.value }), _jsxs("span", { className: "text-emerald-500 text-xs font-bold flex items-center", children: [_jsx(ArrowUpRight, { className: "w-3 h-3 mr-0.5" }), "4.2%"] })] })] }, stat.name));
                                }) }), _jsxs("div", { className: "bg-white rounded-[2rem] shadow-[0_8px_40px_rgb(0,0,0,0.03)] border border-slate-100 overflow-hidden", children: [_jsxs("div", { className: "p-8 border-b border-slate-100 flex items-center justify-between bg-slate-50/50", children: [_jsx("h3", { className: "font-black text-slate-900 text-xl tracking-tight uppercase italic", children: "Active Tenant Registry" }), _jsxs("div", { className: "flex space-x-2", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-emerald-500" }), _jsx("span", { className: "w-2 h-2 rounded-full bg-amber-500" }), _jsx("span", { className: "w-2 h-2 rounded-full bg-red-400" })] })] }), _jsxs("table", { className: "w-full text-left", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-100 bg-slate-50/30", children: [_jsx("th", { className: "px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]", children: "Tenant Entity" }), _jsx("th", { className: "px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]", children: "Instance Slug" }), _jsx("th", { className: "px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]", children: "Plan Vector" }), _jsx("th", { className: "px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]", children: "User Load" }), _jsx("th", { className: "px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]", children: "Lifecycle" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-50", children: dummyTenants.map((tenant) => (_jsxs("tr", { className: "hover:bg-indigo-50/30 transition-all cursor-pointer", children: [_jsx("td", { className: "px-8 py-6 font-bold text-slate-800", children: tenant.name }), _jsxs("td", { className: "px-8 py-6 text-indigo-400 font-mono text-sm", children: [tenant.slug, ".saas.com"] }), _jsx("td", { className: "px-8 py-6 font-medium text-slate-600", children: tenant.plan }), _jsx("td", { className: "px-8 py-6 font-black text-slate-900", children: tenant.users.toLocaleString() }), _jsx("td", { className: "px-8 py-6", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: `w-2 h-2 rounded-full ${tenant.status === 'Active' ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]' :
                                                                            tenant.status === 'Trial' ? 'bg-amber-400' : 'bg-red-500'}` }), _jsx("span", { className: "text-xs font-bold text-slate-700", children: tenant.status })] }) })] }, tenant.id))) })] })] })] })] })] }));
};
export default AdminDashboard;
